language: node_js
notifications:
  slack:
    secure: L+NOiygRw1SDgOP16WMFWxyedMh+I4IHozmgIJ6o25AF0UPH2E5njmTHJBkObav1g5vsqSEV3Rl3pg4tw0NVbAlZ4TBq18z4U+JmSg4CUQ5XFIYr070AN9YvR7W+W10mCgPFoGN0z4URldSCo9GrqprVRWxOIVzukqJQQsm6WhHGcbXXs72axmvR7bD2LCtLA5Z+XlCyRds88vye73sBNLsPonxDYnfx33AeLaUGWSKStRrN0promwY92oATs7DSlEZC+Zk74jzLSfNXPjZn9bKq9Y7yrBwwOmwcL+SEdPAhdxTytzP4YJE7JdmTvu4NDsl+J/cmGIE+lmLWqsBeqP1qiUMVDQ1qqrZtVoC5oRmpNCc+izaD/rRoaqSl3neFnpDElEDKMuMmnqJPOFTCA7BH+61VJjkz5ZRHz+Nuplvc6tdWlRIt/sbaf19pif+WJWZCkbqHrKmRG/Cv+83OysydsAlUAtn7JBHa23XhYM9rb7ZUgV0gh/QCcDPlDwGY28ItLPJhz43QOkIfleKh0VW68NIvB2OkG7E/z4NN7Om/xuif9kmCPOpdQJPsVYM+nxGBb5YK8Zf55U1Oom2xpMJCADjo2hLm3LxNmG6Boc/+5o7i++x6UKstycjUmr+b5HUBl8K4iSNvqZjOOfz6K0/kIUnhRQ1Tg89Oem8shK8=
deploy:
  provider: heroku
  api_key:
    secure: RB6Yxs0JVMUqnXLrr2gmvf/wZ4J5WseuyI1pFs+8jJUjtgTB3kshgyJ2poxvBRXXoo0f3WYTRJMQUYzsYKEG/znIEnkJsj6s7nkk0Dv49ZBOKgvy3yFTApgwevPnWfgxRqm0jkXucqsY7Y5DGxdLjNJkfdZYE/TELQHfv6CpkcQrurUl3R7WWr4Nqtfgk/iYovrRQaE42XTq0t/Igcfuhps2l+4T4OYUVbNBt8BNgLUkh0B7r8eyKFk8O5T+gu0HcyICRnc/Anx7EMguMEamMmoYF2xzOUhBNSwkeiQl6bsMYO+EtYaROUjybqI+L5cpTlrmDprCbsXmHz38HLM37CvvLsc0ovVIpb5+MOvYKxpW0QwipDp+fTzBkPSGwNQ2B1SzFtfzSDzW4XArdNpBvqMYA4c/ToJ9nZqtBJkKOihpUQWNtFfaPjJgPkBT1Dwp42+Syog3hNDA25ApolmKnrXDL1v3797LJ40MrbQXjTGCMKuV5+Kr2wuW7KVaLRu/qmSp5pCDdLWJSRd8iq+ZYZ+8+BMpvo6K2PLu2BLXCbusmHhO9D+qc9Q0hOqcOD6A7uz17AZ1RwfK36SQPeJLmhhtTMlRm3CmUEveU+Lc2kU9AAy1eh3cE0DnFzDFV7jWN2FGupYZ+aytJuwI4/aEA3hClAJSi2UqOB2nCeWpxq4=
  app: applesauce
  on:
    repo: unnamedstudios/applesauce
    branch: master
