language: node_js
notifications:
  slack:
    secure: L+NOiygRw1SDgOP16WMFWxyedMh+I4IHozmgIJ6o25AF0UPH2E5njmTHJBkObav1g5vsqSEV3Rl3pg4tw0NVbAlZ4TBq18z4U+JmSg4CUQ5XFIYr070AN9YvR7W+W10mCgPFoGN0z4URldSCo9GrqprVRWxOIVzukqJQQsm6WhHGcbXXs72axmvR7bD2LCtLA5Z+XlCyRds88vye73sBNLsPonxDYnfx33AeLaUGWSKStRrN0promwY92oATs7DSlEZC+Zk74jzLSfNXPjZn9bKq9Y7yrBwwOmwcL+SEdPAhdxTytzP4YJE7JdmTvu4NDsl+J/cmGIE+lmLWqsBeqP1qiUMVDQ1qqrZtVoC5oRmpNCc+izaD/rRoaqSl3neFnpDElEDKMuMmnqJPOFTCA7BH+61VJjkz5ZRHz+Nuplvc6tdWlRIt/sbaf19pif+WJWZCkbqHrKmRG/Cv+83OysydsAlUAtn7JBHa23XhYM9rb7ZUgV0gh/QCcDPlDwGY28ItLPJhz43QOkIfleKh0VW68NIvB2OkG7E/z4NN7Om/xuif9kmCPOpdQJPsVYM+nxGBb5YK8Zf55U1Oom2xpMJCADjo2hLm3LxNmG6Boc/+5o7i++x6UKstycjUmr+b5HUBl8K4iSNvqZjOOfz6K0/kIUnhRQ1Tg89Oem8shK8=
addons:
    code_climate:
        repo_token: 6b1c343ad8f7b18febdd3fc8ba814d6de7a1fed740fa26b19bfae11a694741ba
after_script:
  - CODECLIMATE_REPO_TOKEN=6b1c343ad8f7b18febdd3fc8ba814d6de7a1fed740fa26b19bfae11a694741ba codeclimate-test-reporter < coverage/lcov.info
script:
  - "npm test --coverage"
  - "node ./node_modules/.bin/istanbul check-coverage --statements 90 --branches 90 --lines 90 --functions 90"
